name: Build IzPack Installer with Custom Panels

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '7'

      - name: Create target directories
        run: |
          mkdir -p target/classes
          mkdir -p target/jar
          mkdir -p target/installer

      - name: Compile Custom Panels
        run: |
          javac -d target/classes -cp lib/izpack-dist-5.2.3.jar $(find src/main/java/com/izforge/izpack/panels/xstprocess -name "*.java")

      - name: Package Custom Panels into JAR
        run: |
          jar cf target/jar/izpack-panels.jar -C target/classes .

      - name: Ensure Installation Descriptor
        run: |
          cp src/main/resources/install.xml target/install.xml

      - name: Build IzPack Installer
        run: |
          java -jar lib/izpack-dist-5.2.3.jar target/install.xml -b src -o target/installer/your-installer.jar

      - name: List target directory
        run: ls -R target

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: target/installer/your-installer.jar
          if-no-files-found: error
